### ISSUE TITLE
[BUG] - El seek no funciona

### ISSUE THREAD

**Issue by AleixFerre** [AleixFerre/CataBot#149]
ReferenceError: guild is not defined

Al executar
!p https://www.youtube.com/watch?v=SKGhejJjsY8
!seek 2292

**Comment by AleixFerre** [comment]
Log:

```
 Jul 09 03:06:28 catabot app/worker.1 ReferenceError: guild is not defined
 Jul 09 03:06:28 catabot app/worker.1     at seekSecond (/app/lib/musicModule.js:818:18)
 Jul 09 03:06:28 catabot app/worker.1     at Object.execute (/app/commands/Musica/segon.js:38:5)
 Jul 09 03:06:28 catabot app/worker.1     at Client.<anonymous> (/app/app.js:344:13)
 Jul 09 03:06:28 catabot app/worker.1     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by AleixFerre** [comment]
Si el bot fa un seek no es mostra correctament al NowPlaying
